"""Regenerate docs/compatibility.md by running the engine over every deck here.

    python scripts/compatibility_matrix.py            # write the doc
    python scripts/compatibility_matrix.py --check    # fail if it has drifted

Every row is produced by an edit that actually ran on this machine. A construct
no available deck contains comes out UNKNOWN, and there is no way to give it a
verdict except to find a deck that has one.

The edit is deliberately the smallest one the engine can perform: the first text
run it finds, replaced with itself plus a character. What is being measured is
not the edit. It is everything the edit did not touch.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src" / "engine"))

from slide_wright.apply import apply_changes  # noqa: E402
from slide_wright.changeset import Change, ChangeSet, Op  # noqa: E402
from slide_wright.compatibility import UNKNOWN, measure  # noqa: E402
from slide_wright.inspect import inspect  # noqa: E402

DOC = ROOT / "docs" / "compatibility.md"
CORPUS = ROOT / "tests" / "corpus"
FIXTURES = ROOT / "tests" / "fixtures" / "third-party"

HEADER = """# Compatibility

*Generated by `scripts/compatibility_matrix.py`. Do not edit by hand — every
row here is the result of an edit that actually ran, and a row written by hand
would be indistinguishable from one that was measured.*

Two columns, answering two different questions.

**Preserved through an edit** is a measurement. A deck containing the construct
was edited, and the parts carrying that construct were compared byte-for-byte
against the original. For a construct with parts of its own — a chart, a
diagram, an embedded workbook — the claim is exact. For one that lives inside
slide XML the carrier is the slide, which an edit changes on purpose, so the
claim is the weaker one: nothing was removed and no native object was lost.

**Editing** is a decision in the code, not a measurement. `REFUSED` means the
engine declines to change that construct and says so rather than trying. The
other value is *not refused*, not "supported": there is no guard against editing
an OLE object and also no way to edit one, and calling that "allowed" would be
the same overclaim as a ticked row nobody measured.

**UNKNOWN means no deck on the machine that generated this contains the
construct.** It is not a soft no and not a warning. Nothing was measured, so
nothing is claimed. Adding a deck that contains one is the only way to change
it.
"""


def smallest_edit(deck: Path, output: Path) -> Path | None:
    """Change one text run, and nothing else. Returns None if there is none."""
    info = inspect(deck)
    for slide in info.slides:
        for shape in slide.shapes:
            if shape.kind in ("table", "chart") or not shape.runs:
                continue
            run = next((r for r in shape.runs if r.text.strip()), None)
            if run is None:
                continue
            changeset = ChangeSet(deck=str(deck))
            changeset.add(Change(
                id="m1", op=Op.SET_TEXT, slide=slide.number, target=shape.id,
                before=run.text, after=run.text + ".",
            ))
            changeset.approve_all()
            try:
                result = apply_changes(deck, changeset, output)
            except Exception:
                continue
            if result.ok:
                return output
    return None


def decks() -> list[Path]:
    found = sorted(CORPUS.glob("*.pptx"))
    if FIXTURES.is_dir():
        found += sorted(FIXTURES.glob("*.pptx"))
    return found


def build() -> str:
    tmp = Path(tempfile.mkdtemp())
    pairs, skipped = [], []
    for deck in decks():
        edited = smallest_edit(deck, tmp / f"{deck.stem}-edited.pptx")
        if edited is None:
            skipped.append(deck.name)
            continue
        pairs.append((deck, edited))

    if not pairs:
        raise SystemExit(
            "no deck here could be edited, so nothing can be measured. "
            "Run scripts/fetch_fixtures.py first."
        )

    matrix = measure(pairs)
    body = [
        HEADER,
        f"Measured over **{len(matrix.decks)} deck(s)** on this machine.",
        "",
        matrix.render(),
        "",
    ]
    if matrix.unknown:
        body += [
            "## Not measured",
            "",
            "No deck available here contains these, so the engine's behaviour "
            "with them is unknown. They are listed rather than omitted, because "
            "a construct missing from a compatibility table reads as one that "
            "was considered and found fine.",
            "",
        ]
        body += [f"- {row.construct.name}" for row in matrix.unknown]
        body.append("")
    notes = [r for r in matrix.rows if r.construct.note and r.decks_containing]
    if notes:
        body += ["## Refusals, and why", ""]
        for row in notes:
            body.append(
                f"- **{row.construct.name}** — {row.construct.note} "
                f"(`{row.construct.refused_because}`)"
            )
        body.append("")
    if skipped:
        body += [
            "## Decks with nothing editable",
            "",
            "Present, opened and read, but holding no text run this engine "
            "could change — so they contributed nothing to the measurements "
            "above.",
            "",
        ]
        body += [f"- {name}" for name in skipped]
        body.append("")
    shutil.rmtree(tmp, ignore_errors=True)
    return "\n".join(body)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the checked-in doc no longer matches")
    args = parser.parse_args(argv)

    generated = build()
    if args.check:
        if not DOC.is_file():
            print(f"{DOC} does not exist; run this without --check")
            return 1
        if DOC.read_text(encoding="utf-8") != generated:
            print(f"{DOC.relative_to(ROOT)} is out of date. Regenerate it:")
            print("    python scripts/compatibility_matrix.py")
            return 1
        print(f"{DOC.relative_to(ROOT)} matches what the engine measures.")
        return 0

    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text(generated, encoding="utf-8")
    unknown = generated.count(UNKNOWN)
    print(f"wrote {DOC.relative_to(ROOT)} ({unknown} UNKNOWN)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
